# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/frontend/*
      - azure-pipelines-frontend.yml

pool:
  vmImage: 'windows-latest'

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: 'src/frontend'

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: 'custom'
      workingDir: 'src/frontend'
      customCommand: 'run build -- --prod'

  - task: Npm@1
    displayName: 'npm test-ci'
    inputs:
      command: custom
      workingDir: 'src/frontend'
      verbose: false
      customCommand: 'run test-ci'
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TESTS-*.xml'
    inputs:
      testResultsFiles: '**/TESTS-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/src/frontend/junit'
      failTaskOnFailedTests: true

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from src/frontend/coverage/ToDoListApp/cobertura-coverage.xml'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'src/frontend/coverage/ToDoListApp/cobertura-coverage.xml'
      failIfCoverageEmpty: true
